// Generated by CoffeeScript 1.3.3
(function() {
  var Flow, FlowStep, flow,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __slice = [].slice;

  FlowStep = (function() {

    function FlowStep(func, lastReturn, ops, callback) {
      var op;
      this.callback = callback;
      this.next = __bind(this.next, this);

      this._next = __bind(this._next, this);

      this.spawn = __bind(this.spawn, this);

      for (op in ops) {
        this[op] = ops[op];
      }
      this.threads = [];
      this._unjoinedThreadCount = 1;
      try {
        lastReturn.unshift(this);
        func.apply(null, lastReturn);
      } catch (ex) {
        console.log(ex);
        this.callback([ex]);
      }
    }

    FlowStep.prototype.raise = function(ex) {
      throw ex;
    };

    FlowStep.prototype.spawn = function() {
      var threadId,
        _this = this;
      this._unjoinedThreadCount++;
      threadId = this.threads.length;
      this.threads.push([void 0]);
      return function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        args.unshift(void 0);
        _this.threads[threadId] = args;
        _this._unjoinedThreadCount--;
        return _this._next();
      };
    };

    FlowStep.prototype._next = function() {
      if (this._unjoinedThreadCount === 0) {
        if (this.threads.length === 1) {
          this.threads = this.threads[0];
        }
        return this.callback(this.threads);
      }
    };

    FlowStep.prototype.next = function() {
      if (arguments.length > 0) {
        this.spawn().apply(null, arguments);
      }
      this._unjoinedThreadCount--;
      this._next();
    };

    return FlowStep;

  })();

  Flow = (function() {

    function Flow(steps, ops, callback) {
      this.steps = steps;
      if (ops == null) {
        ops = null;
      }
      if (callback == null) {
        callback = null;
      }
      this.run = __bind(this.run, this);

      if (!(callback != null)) {
        callback = ops;
        ops = null;
      }
      if (!(callback != null)) {
        callback = function() {};
      }
      if (!(ops != null)) {
        ops = {};
      }
      this.steps.push(callback);
      this.ops = ops;
    }

    Flow.prototype.run = function() {
      var i, _run,
        _this = this;
      i = -1;
      _run = function(lastReturn) {
        i++;
        if (i < _this.steps.length) {
          return new FlowStep(_this.steps[i], lastReturn, _this.ops, _run);
        }
      };
      _run([void 0]);
    };

    return Flow;

  })();

  flow = function(steps, ops, callback) {
    (new Flow(steps, ops, callback)).run();
  };

  if (typeof window === 'undefined') {
    module.exports = flow;
  } else {
    window.flow = flow;
  }

}).call(this);
